FROM apache/airflow:latest

# Switch to root user to install system dependencies
USER root

# Install git (already included) and any other required dependencies
RUN apt-get update && \
    apt-get -y install git && \
    apt-get clean

# Switch back to the airflow user
USER airflow

RUN pip install apache-airflow-providers-dbt-cloud
RUN pip install apache-airflow-providers-amazon


